"""initial quant core schema

Revision ID: e90def444b1f
Revises:
Create Date: 2026-08-18 08:13:46.932733
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e90def444b1f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_cycles",
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pipeline_version", sa.String(length=128), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("cycle_id"),
    )
    op.create_table(
        "analysis_workflow_runs",
        sa.Column("workflow_id", sa.String(length=128), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("workflow_id"),
        sa.UniqueConstraint("cycle_id"),
    )
    op.create_table(
        "architecture_decisions",
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_table(
        "change_proposals",
        sa.Column("proposal_id", sa.String(length=128), nullable=False),
        sa.Column("base_version", sa.String(length=128), nullable=False),
        sa.Column("change_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("proposal_id"),
    )
    op.create_table(
        "codex_account_capacity",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_headroom", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("healthy", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("account_id", "observed_at"),
    )
    op.create_table(
        "codex_account_leases",
        sa.Column("lease_id", sa.String(length=128), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("attempt_id", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("lease_id"),
        sa.UniqueConstraint("attempt_id"),
    )
    op.create_index(
        "uq_active_codex_account_lease",
        "codex_account_leases",
        ["account_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
        sqlite_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "codex_runs",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_class", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "evaluation_plans",
        sa.Column("plan_id", sa.String(length=128), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("base_manifest_id", sa.String(length=128), nullable=False),
        sa.Column("regression_suite_version", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("plan_id"),
    )
    op.create_table(
        "evaluation_results",
        sa.Column("evaluation_id", sa.String(length=128), nullable=False),
        sa.Column("proposal_id", sa.String(length=128), nullable=False),
        sa.Column("plan_id", sa.String(length=128), nullable=False),
        sa.Column("candidate_manifest_id", sa.String(length=128), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("evaluation_id"),
    )
    op.create_table(
        "failed_experiments",
        sa.Column("experiment_id", sa.String(length=128), nullable=False),
        sa.Column("hypothesis_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("experiment_id"),
    )
    op.create_index(
        "ix_failed_experiment_fingerprint",
        "failed_experiments",
        ["hypothesis_fingerprint"],
        unique=False,
    )
    op.create_table(
        "governance_snapshots",
        sa.Column("snapshot_id", sa.String(length=128), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("champion_manifest_id", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("snapshot_id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_table(
        "normalized_events",
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("evidence_id"),
        sa.UniqueConstraint("source", "content_hash", name="uq_normalized_event_source_hash"),
    )
    op.create_table(
        "portfolio_risk_budgets",
        sa.Column("portfolio_id", sa.String(length=64), nullable=False),
        sa.Column("reserved_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("exposure_risk_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.PrimaryKeyConstraint("portfolio_id"),
    )
    op.bulk_insert(
        sa.table(
            "portfolio_risk_budgets",
            sa.column("portfolio_id", sa.String()),
            sa.column("reserved_amount", sa.Numeric(precision=38, scale=18)),
            sa.column("exposure_risk_amount", sa.Numeric(precision=38, scale=18)),
        ),
        [
            {
                "portfolio_id": "primary",
                "reserved_amount": 0,
                "exposure_risk_amount": 0,
            }
        ],
    )
    op.create_table(
        "release_manifests",
        sa.Column("manifest_id", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("manifest_id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_table(
        "replay_evaluation_reports",
        sa.Column("report_id", sa.String(length=128), nullable=False),
        sa.Column("evaluation_version", sa.String(length=128), nullable=False),
        sa.Column("dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("statistically_conclusive", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.create_table(
        "risk_reservations",
        sa.Column("reservation_id", sa.String(length=128), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("intent_id", sa.String(length=128), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("risk_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("reservation_id"),
        sa.UniqueConstraint("cycle_id"),
        sa.UniqueConstraint("intent_id"),
    )
    op.create_table(
        "system_constitutions",
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "account_snapshots",
        sa.Column("snapshot_id", sa.String(length=128), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("phase", sa.String(length=32), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("reconciled", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["analysis_cycles.cycle_id"],
        ),
        sa.PrimaryKeyConstraint("snapshot_id"),
        sa.UniqueConstraint("cycle_id", "phase", name="uq_account_snapshot_cycle_phase"),
    )
    op.create_table(
        "analysis_proposals",
        sa.Column("proposal_id", sa.String(length=128), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("proposal_type", sa.String(length=32), nullable=False),
        sa.Column("suggested_action", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["analysis_cycles.cycle_id"],
        ),
        sa.PrimaryKeyConstraint("proposal_id"),
        sa.UniqueConstraint("cycle_id"),
    )
    op.create_table(
        "market_snapshots",
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["analysis_cycles.cycle_id"],
        ),
        sa.PrimaryKeyConstraint("cycle_id"),
    )
    op.create_table(
        "metric_observations",
        sa.Column("metric_id", sa.String(length=128), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("phase", sa.String(length=32), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("metric_version", sa.String(length=128), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["analysis_cycles.cycle_id"],
        ),
        sa.PrimaryKeyConstraint("metric_id"),
        sa.UniqueConstraint("cycle_id", "phase", "sequence", name="uq_metric_cycle_phase_sequence"),
    )
    op.create_index(
        "ix_metric_observations_cycle", "metric_observations", ["cycle_id"], unique=False
    )
    op.create_table(
        "panel_snapshots",
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["analysis_cycles.cycle_id"],
        ),
        sa.PrimaryKeyConstraint("cycle_id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_table(
        "signal_candidates",
        sa.Column("candidate_id", sa.String(length=128), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.String(length=128), nullable=False),
        sa.Column("producer_version", sa.String(length=128), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["analysis_cycles.cycle_id"],
        ),
        sa.PrimaryKeyConstraint("candidate_id"),
        sa.UniqueConstraint("cycle_id", "sequence", name="uq_signal_candidate_cycle_sequence"),
    )
    op.create_index("ix_signal_candidates_cycle", "signal_candidates", ["cycle_id"], unique=False)
    op.create_table(
        "trade_intents",
        sa.Column("intent_id", sa.String(length=128), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("pipeline_version", sa.String(length=128), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["analysis_cycles.cycle_id"],
        ),
        sa.PrimaryKeyConstraint("intent_id"),
        sa.UniqueConstraint("cycle_id"),
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.String(length=128), nullable=False),
        sa.Column("client_order_id", sa.String(length=36), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("intent_id", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["analysis_cycles.cycle_id"],
        ),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["trade_intents.intent_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
        sa.UniqueConstraint("client_order_id"),
        sa.UniqueConstraint("cycle_id", "role", name="uq_order_cycle_role"),
    )
    op.create_table(
        "position_lifecycles",
        sa.Column("position_id", sa.String(length=128), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("intent_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["analysis_cycles.cycle_id"],
        ),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["trade_intents.intent_id"],
        ),
        sa.PrimaryKeyConstraint("position_id"),
        sa.UniqueConstraint("cycle_id"),
        sa.UniqueConstraint("intent_id"),
    )
    op.create_table(
        "risk_decisions",
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("intent_id", sa.String(length=128), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("policy_version", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["analysis_cycles.cycle_id"],
        ),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["trade_intents.intent_id"],
        ),
        sa.PrimaryKeyConstraint("decision_id"),
        sa.UniqueConstraint("cycle_id"),
        sa.UniqueConstraint("intent_id"),
    )
    op.create_table(
        "decision_outcomes",
        sa.Column("outcome_id", sa.String(length=128), nullable=False),
        sa.Column("cycle_id", sa.String(length=128), nullable=False),
        sa.Column("intent_id", sa.String(length=128), nullable=False),
        sa.Column("position_id", sa.String(length=128), nullable=False),
        sa.Column("net_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["analysis_cycles.cycle_id"],
        ),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["trade_intents.intent_id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position_lifecycles.position_id"],
        ),
        sa.PrimaryKeyConstraint("outcome_id"),
        sa.UniqueConstraint("cycle_id"),
        sa.UniqueConstraint("intent_id"),
    )
    op.create_table(
        "fills",
        sa.Column("fill_id", sa.String(length=128), nullable=False),
        sa.Column("order_id", sa.String(length=128), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
        ),
        sa.PrimaryKeyConstraint("fill_id"),
    )
    op.create_index("ix_fills_order", "fills", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fills_order", table_name="fills")
    op.drop_table("fills")
    op.drop_table("decision_outcomes")
    op.drop_table("risk_decisions")
    op.drop_table("position_lifecycles")
    op.drop_table("orders")
    op.drop_table("trade_intents")
    op.drop_index("ix_signal_candidates_cycle", table_name="signal_candidates")
    op.drop_table("signal_candidates")
    op.drop_table("panel_snapshots")
    op.drop_index("ix_metric_observations_cycle", table_name="metric_observations")
    op.drop_table("metric_observations")
    op.drop_table("market_snapshots")
    op.drop_table("analysis_proposals")
    op.drop_table("account_snapshots")
    op.drop_table("system_constitutions")
    op.drop_table("risk_reservations")
    op.drop_table("replay_evaluation_reports")
    op.drop_table("release_manifests")
    op.drop_table("portfolio_risk_budgets")
    op.drop_table("normalized_events")
    op.drop_table("governance_snapshots")
    op.drop_index("ix_failed_experiment_fingerprint", table_name="failed_experiments")
    op.drop_table("failed_experiments")
    op.drop_table("evaluation_results")
    op.drop_table("evaluation_plans")
    op.drop_table("codex_runs")
    op.drop_index(
        "uq_active_codex_account_lease",
        table_name="codex_account_leases",
        postgresql_where=sa.text("status = 'ACTIVE'"),
        sqlite_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("codex_account_leases")
    op.drop_table("codex_account_capacity")
    op.drop_table("change_proposals")
    op.drop_table("architecture_decisions")
    op.drop_table("analysis_workflow_runs")
    op.drop_table("analysis_cycles")
    # ### end Alembic commands ###
